mode: ContinuousDelivery
next-version: 0.2.0       # fallback
tag-prefix: '[vV]'
commit-message-incrementing: Enabled
increment: Patch

branches:
  master:
    regex: ^master$
    label: ''                # stable, no pre-release
    increment: Patch
    tracks-release-branches: true

  develop:
    regex: ^develop$
    label: alpha
    increment: Minor
    source-branches: [master]

  release:
    regex: ^release[/-].*$
    label: ''               # treat release branches as stable
    is-release-branch: true
    increment: None
    source-branches: [develop, master]
